version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
  pre_build:
    commands:
      - echo Installing NPM dependencies...
      - npm install
      - CLOUDFRONT_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?AliasICPRecordals[?CNAME=='$WEB_BUCKET']].{ID:Id}" --output text)
      - echo CloudFront ID $CLOUDFRONT_ID
  build:
    commands:
      - REACT_APP_STAGE=${ENVIRONMENT} npm run build
      - mv build/${ENVIRONMENT}.robots.txt build/robots.txt;
      - |
         if expr "${ENVIRONMENT}" : "prod" >/dev/null; then
           rm build/staging.robots.txt
         else
           rm build/prod.robots.txt;
         fi
  post_build:
    commands:
      - echo Uploaded to ${WEB_BUCKET}
      - aws s3 sync build/ s3://${WEB_BUCKET} --delete --exclude 'build/status.html'
      - aws s3 cp build/status.html s3://${WEB_BUCKET}/status.html --cache-control no-cache
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: build
